/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ProjectsProjectKeyRouteImport } from './routes/projects.$projectKey'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as ChatWWorkspaceIdIndexRouteImport } from './routes/_chat.w.$workspaceId.index'
import { Route as ChatWWorkspaceIdThreadIdRouteImport } from './routes/_chat.w.$workspaceId.$threadId'
import { Route as ChatWWorkspaceIdCiRouteImport } from './routes/_chat.w.$workspaceId.ci'
import { Route as ChatWWorkspaceIdCodeMapRouteImport } from './routes/_chat.w.$workspaceId.code-map'
import { Route as ChatWWorkspaceIdPullRequestsRouteImport } from './routes/_chat.w.$workspaceId.pull-requests'
import { Route as ChatWWorkspaceIdReposRouteImport } from './routes/_chat.w.$workspaceId.repos'
import { Route as ChatWWorkspaceIdDraftDraftIdRouteImport } from './routes/_chat.w.$workspaceId.draft.$draftId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ProjectsProjectKeyRoute = ProjectsProjectKeyRouteImport.update({
  id: '/projects/$projectKey',
  path: '/projects/$projectKey',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatWWorkspaceIdIndexRoute = ChatWWorkspaceIdIndexRouteImport.update({
  id: '/w/$workspaceId/',
  path: '/w/$workspaceId/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWWorkspaceIdThreadIdRoute =
  ChatWWorkspaceIdThreadIdRouteImport.update({
    id: '/w/$workspaceId/$threadId',
    path: '/w/$workspaceId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatWWorkspaceIdCiRoute = ChatWWorkspaceIdCiRouteImport.update({
  id: '/w/$workspaceId/ci',
  path: '/w/$workspaceId/ci',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWWorkspaceIdCodeMapRoute = ChatWWorkspaceIdCodeMapRouteImport.update({
  id: '/w/$workspaceId/code-map',
  path: '/w/$workspaceId/code-map',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWWorkspaceIdPullRequestsRoute =
  ChatWWorkspaceIdPullRequestsRouteImport.update({
    id: '/w/$workspaceId/pull-requests',
    path: '/w/$workspaceId/pull-requests',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatWWorkspaceIdReposRoute = ChatWWorkspaceIdReposRouteImport.update({
  id: '/w/$workspaceId/repos',
  path: '/w/$workspaceId/repos',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWWorkspaceIdDraftDraftIdRoute =
  ChatWWorkspaceIdDraftDraftIdRouteImport.update({
    id: '/w/$workspaceId/draft/$draftId',
    path: '/w/$workspaceId/draft/$draftId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/w/$workspaceId/$threadId': typeof ChatWWorkspaceIdThreadIdRoute
  '/w/$workspaceId/ci': typeof ChatWWorkspaceIdCiRoute
  '/w/$workspaceId/code-map': typeof ChatWWorkspaceIdCodeMapRoute
  '/w/$workspaceId/pull-requests': typeof ChatWWorkspaceIdPullRequestsRoute
  '/w/$workspaceId/repos': typeof ChatWWorkspaceIdReposRoute
  '/w/$workspaceId/': typeof ChatWWorkspaceIdIndexRoute
  '/w/$workspaceId/draft/$draftId': typeof ChatWWorkspaceIdDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/': typeof ChatIndexRoute
  '/w/$workspaceId/$threadId': typeof ChatWWorkspaceIdThreadIdRoute
  '/w/$workspaceId/ci': typeof ChatWWorkspaceIdCiRoute
  '/w/$workspaceId/code-map': typeof ChatWWorkspaceIdCodeMapRoute
  '/w/$workspaceId/pull-requests': typeof ChatWWorkspaceIdPullRequestsRoute
  '/w/$workspaceId/repos': typeof ChatWWorkspaceIdReposRoute
  '/w/$workspaceId': typeof ChatWWorkspaceIdIndexRoute
  '/w/$workspaceId/draft/$draftId': typeof ChatWWorkspaceIdDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/w/$workspaceId/$threadId': typeof ChatWWorkspaceIdThreadIdRoute
  '/_chat/w/$workspaceId/ci': typeof ChatWWorkspaceIdCiRoute
  '/_chat/w/$workspaceId/code-map': typeof ChatWWorkspaceIdCodeMapRoute
  '/_chat/w/$workspaceId/pull-requests': typeof ChatWWorkspaceIdPullRequestsRoute
  '/_chat/w/$workspaceId/repos': typeof ChatWWorkspaceIdReposRoute
  '/_chat/w/$workspaceId/': typeof ChatWWorkspaceIdIndexRoute
  '/_chat/w/$workspaceId/draft/$draftId': typeof ChatWWorkspaceIdDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/usage'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/source-control'
    | '/w/$workspaceId/$threadId'
    | '/w/$workspaceId/ci'
    | '/w/$workspaceId/code-map'
    | '/w/$workspaceId/pull-requests'
    | '/w/$workspaceId/repos'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/usage'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/source-control'
    | '/'
    | '/w/$workspaceId/$threadId'
    | '/w/$workspaceId/ci'
    | '/w/$workspaceId/code-map'
    | '/w/$workspaceId/pull-requests'
    | '/w/$workspaceId/repos'
    | '/w/$workspaceId'
    | '/w/$workspaceId/draft/$draftId'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/usage'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/source-control'
    | '/_chat/'
    | '/_chat/w/$workspaceId/$threadId'
    | '/_chat/w/$workspaceId/ci'
    | '/_chat/w/$workspaceId/code-map'
    | '/_chat/w/$workspaceId/pull-requests'
    | '/_chat/w/$workspaceId/repos'
    | '/_chat/w/$workspaceId/'
    | '/_chat/w/$workspaceId/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  UsageRoute: typeof UsageRoute
  ProjectsProjectKeyRoute: typeof ProjectsProjectKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/projects/$projectKey': {
      id: '/projects/$projectKey'
      path: '/projects/$projectKey'
      fullPath: '/projects/$projectKey'
      preLoaderRoute: typeof ProjectsProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/w/$workspaceId/': {
      id: '/_chat/w/$workspaceId/'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof ChatWWorkspaceIdIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/w/$workspaceId/$threadId': {
      id: '/_chat/w/$workspaceId/$threadId'
      path: '/w/$workspaceId/$threadId'
      fullPath: '/w/$workspaceId/$threadId'
      preLoaderRoute: typeof ChatWWorkspaceIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/w/$workspaceId/ci': {
      id: '/_chat/w/$workspaceId/ci'
      path: '/w/$workspaceId/ci'
      fullPath: '/w/$workspaceId/ci'
      preLoaderRoute: typeof ChatWWorkspaceIdCiRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/w/$workspaceId/code-map': {
      id: '/_chat/w/$workspaceId/code-map'
      path: '/w/$workspaceId/code-map'
      fullPath: '/w/$workspaceId/code-map'
      preLoaderRoute: typeof ChatWWorkspaceIdCodeMapRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/w/$workspaceId/pull-requests': {
      id: '/_chat/w/$workspaceId/pull-requests'
      path: '/w/$workspaceId/pull-requests'
      fullPath: '/w/$workspaceId/pull-requests'
      preLoaderRoute: typeof ChatWWorkspaceIdPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/w/$workspaceId/repos': {
      id: '/_chat/w/$workspaceId/repos'
      path: '/w/$workspaceId/repos'
      fullPath: '/w/$workspaceId/repos'
      preLoaderRoute: typeof ChatWWorkspaceIdReposRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/w/$workspaceId/draft/$draftId': {
      id: '/_chat/w/$workspaceId/draft/$draftId'
      path: '/w/$workspaceId/draft/$draftId'
      fullPath: '/w/$workspaceId/draft/$draftId'
      preLoaderRoute: typeof ChatWWorkspaceIdDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatWWorkspaceIdThreadIdRoute: typeof ChatWWorkspaceIdThreadIdRoute
  ChatWWorkspaceIdCiRoute: typeof ChatWWorkspaceIdCiRoute
  ChatWWorkspaceIdCodeMapRoute: typeof ChatWWorkspaceIdCodeMapRoute
  ChatWWorkspaceIdPullRequestsRoute: typeof ChatWWorkspaceIdPullRequestsRoute
  ChatWWorkspaceIdReposRoute: typeof ChatWWorkspaceIdReposRoute
  ChatWWorkspaceIdIndexRoute: typeof ChatWWorkspaceIdIndexRoute
  ChatWWorkspaceIdDraftDraftIdRoute: typeof ChatWWorkspaceIdDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatWWorkspaceIdThreadIdRoute: ChatWWorkspaceIdThreadIdRoute,
  ChatWWorkspaceIdCiRoute: ChatWWorkspaceIdCiRoute,
  ChatWWorkspaceIdCodeMapRoute: ChatWWorkspaceIdCodeMapRoute,
  ChatWWorkspaceIdPullRequestsRoute: ChatWWorkspaceIdPullRequestsRoute,
  ChatWWorkspaceIdReposRoute: ChatWWorkspaceIdReposRoute,
  ChatWWorkspaceIdIndexRoute: ChatWWorkspaceIdIndexRoute,
  ChatWWorkspaceIdDraftDraftIdRoute: ChatWWorkspaceIdDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  UsageRoute: UsageRoute,
  ProjectsProjectKeyRoute: ProjectsProjectKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
